name: Feature Request
description: Tell us about your feature request
title: "[Feature Request]: "
labels: ["enhancement"]
assignees:
  - curryducker
body:
  - type: textarea
    id: request
    attributes:
      label: Feature Request
      description: Tell us about your request! We don't guarantee that we will actually accept it!
      placeholder: Your very cool feature request!
    validations:
      required: true
